### PR TITLE
embarrassing 'bug' fix in chunk_list so identical to chunk_grp_list

### PR DESCRIPTION
**Pull request by dpastoor**
per @kylebmetrum catch in #34

### CODE REVIEW

**Comment by dpastoor** [comment]
chunk_list and chunk_grp_list now behave as they are described

```
chunk_list(c(letters[1], letters[1], letters[1:7]), 3)
#> [[1]]
#> [1] "a" "a" "a"
#> 
#> [[2]]
#> [1] "b" "c" "d"
#> 
#> [[3]]
#> [1] "e" "f" "g"
#> 

# in this case ragged arrays will be created to keep the number of 
# unique elements consistent as possible between chunks
chunk_grp_list(c(letters[1], letters[1], letters[1:7]), 3)
#> [[1]]
#> [1] "a" "a" "a" "b" "c"
#> 
#> [[2]]
#> [1] "d" "e"
#> 
#> [[3]]
#> [1] "f" "g"
#> 
```

**Comment by dpastoor** [comment]
@kylebmetrum differences make sense now?

**Comment by kylebmetrum** [comment]
I got it now.  Nice to have the flexibility here. Thanks!

**Comment by dpastoor** [comment]
great - redoc'd an submitted to CRAN

**Comment by dpastoor** [comment]
@kylebmetrum this has been accepted to CRAN and will be available shortly. Available as of package version 2.1.1

Thanks for the request and the check.

**Pull request merged**
